# Mirrors config rows where category='product_unit_status'
PRODUCT_UNIT_IN_STOCK = 1
PRODUCT_UNIT_ISSUED = 2
PRODUCT_UNIT_WASTED = 3
PRODUCT_UNIT_IN_TRANSIT = 4

TRANSFER_IN_TRANSIT = 1
TRANSFER_RECEIVED = 2